### ISSUE TITLE
fix google conversion tracking scripts

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/pdap.io#135]
### Context
We have a google ads grant and google tag conversion tracking set up, but it's not working properly. I've tried troubleshooting it but did not have the right experience:patience. Without conversion tracking, we're not routing people to our site effectively enough.

### Requirements
- [ ] consider a helper like: https://github.com/MatteoGabriele/vue-analytics
- [ ] you: reach out! I think we'll need to meet for a few minutes so I can make changes / feed you what you need from the google admin.
- [ ] me: audit the adwords themselves. we're due for this. bring them more in line with the data hub concept, orient toward people asking questions.

**Comment by josh-chamberlain** [comment]
@joshuagraber any chance you'd be able to look at this while you're in there? i'm sure i've made some simple mistake. maybe we can knock it out real quick when we check in next, since you'll likely need my analytics access.
